In [31]:
import ML_utils as mlu
reload(mlu)
import pandas as pd

In [43]:
#dtype = {'MonthlyCharges': float, 'TotalCharges': float}

odf = pd.read_csv('WA_Fn-UseC_-Telco-Customer-Churn.csv', encoding='utf8', 
                  #dtype=dtype
                 )

In [44]:
odf.columns

Index([u'customerID', u'gender', u'SeniorCitizen', u'Partner', u'Dependents',
       u'tenure', u'PhoneService', u'MultipleLines', u'InternetService',
       u'OnlineSecurity', u'OnlineBackup', u'DeviceProtection', u'TechSupport',
       u'StreamingTV', u'StreamingMovies', u'Contract', u'PaperlessBilling',
       u'PaymentMethod', u'MonthlyCharges', u'TotalCharges', u'Churn'],
      dtype='object')

In [34]:
result = u'Churn'

In [35]:
two_valued_str = []

for c in odf.columns:
    if (len(odf[c].value_counts()) == 2) & (mlu.is_categorical(odf, c)):
        two_valued_str.append(c)
        print c, odf[c].dtype
print two_valued_str

gender object
Partner object
Dependents object
PhoneService object
PaperlessBilling object
Churn object
[u'gender', u'Partner', u'Dependents', u'PhoneService', u'PaperlessBilling', u'Churn']

In [36]:
odf2 = odf.copy()

for f in two_valued_str:
    odf2[f] = (odf2[f] == 'Yes').astype(int)

In [46]:
charge_feats = ['TotalCharges', 'MonthlyCharges']:

for f in charge_feats:
    odf2[f] = odf2[f].replace('', np.nan)
    odf2[f]

           11
20.2       11
19.75       9
19.9        8
20.05       8
19.65       8
19.55       7
45.3        7
19.45       6
20.15       6
20.25       6
20.45       5
20.3        5
69.95       4
44          4
19.3        4
44.4        4
70.6        4
20.4        4
20.5        4
19.4        4
19.85       4
50.15       4
49.9        4
74.7        4
69.9        4
75.3        4
69.65       4
19.95       4
19.2        4
           ..
7413.55     1
3777.15     1
1137.05     1
2419        1
219.65      1
1647        1
7852.4      1
412.55      1
6697.2      1
3161.6      1
3161.4      1
1951        1
697.65      1
7349.35     1
5638.3      1
7129.45     1
4663.4      1
716.1       1
92.25       1
5753.25     1
5601.4      1
3165.6      1
2684.85     1
662.95      1
4174.35     1
930.95      1
4630.2      1
75.75       1
7101.5      1
59.25       1
Name: TotalCharges, dtype: int64

In [40]:
odf2['TotalCharges'] / odf2['MonthlyCharges']

TypeError: ufunc 'true_divide' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

In [41]:

odf2['TotalCharges'][0]

u'29.85'

In [ ]:
def year_period(df, date):
    df[date]

In [38]:
odf2[result].value_counts()

0    5174
1    1869
Name: Churn, dtype: int64

In [29]:
mlu.print_full(odf2, n=10)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,0,0,1,0,1,0,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,1,Electronic check,29.85,29.85,0
1,5575-GNVDE,0,0,0,0,34,1,No,DSL,Yes,No,Yes,No,No,No,One year,0,Mailed check,56.95,1889.5,0
2,3668-QPYBK,0,0,0,0,2,1,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,1,Mailed check,53.85,108.15,1
3,7795-CFOCW,0,0,0,0,45,0,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,0,Bank transfer (automatic),42.30,1840.75,0
4,9237-HQITU,0,0,0,0,2,1,No,Fiber optic,No,No,No,No,No,No,Month-to-month,1,Electronic check,70.70,151.65,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,0,0,1,1,24,1,Yes,DSL,Yes,No,Yes,Yes,Yes,Yes,One year,1,Mailed check,84.80,1990.5,0
7039,2234-XADUH,0,0,1,1,72,1,Yes,Fiber optic,No,Yes,Yes,No,Yes,Yes,One year,1,Credit card (automatic),103.20,7362.9,0
7040,4801-JZAZL,0,0,1,1,11,0,No phone service,DSL,Yes,No,No,No,No,No,Month-to-month,1,Electronic check,29.60,346.45,0
7041,8361-LTMKD,0,1,1,0,4,1,Yes,Fiber optic,No,No,No,No,No,No,Month-to-month,1,Mailed check,74.40,306.6,1
7042,3186-AJIEK,0,0,0,0,66,1,No,Fiber optic,Yes,No,Yes,Yes,Yes,Yes,Two year,1,Bank transfer (automatic),105.65,6844.5,0